## 🌍 Introduction

Climate change is one of the most important global challenges of our time. 🌱 Governments, researchers, and organizations around the world are increasingly using data to better understand how human activities affect the environment. By analyzing greenhouse gas emissions across countries, industries, and time periods, we can gain valuable insights into the patterns and trends that shape our planet’s climate. 📊

In this project, we explore a dataset containing quarterly indicators related to greenhouse gas emissions. The data allows us to observe how emissions evolve over time, how different industries contribute to environmental impact, and how patterns vary across countries and economic regions. Looking at these trends can help highlight which sectors play the largest role in emissions and where efforts toward sustainability might have the greatest impact. 🌎

To guide this analysis, the following key questions are considered:

🔎 **Research Questions**

* How have greenhouse gas emissions changed over time across countries and industries?
* Which industries contribute the most to overall emissions levels?
* Are there noticeable differences in emissions patterns between countries or economic regions?
* How do different gas types contribute to total emissions trends?

By answering these questions, this analysis aims to uncover meaningful insights from the data and better understand how economic activity and industrial sectors influence global emissions patterns. 📈✨

---

## 📂 Data Source

The dataset used in this project was obtained from the **Climate Change Indicators Dashboard** maintained by the International Monetary Fund.

This platform compiles climate-related indicators from multiple international sources to support research, policy development, and economic analysis related to climate change. 🌐

**Source:**
[https://climatedata.imf.org/datasets/543872e1d86c49e3a3bdf38f2b758f92/about](https://climatedata.imf.org/datasets/543872e1d86c49e3a3bdf38f2b758f92/about)

### 📥 Loading the Dataset and Libraries

Before we start, we need to install the necessary Python libraries and **load the dataset**.

In [1]:
# Install the required libraries
%pip install pandas numpy matplotlib seaborn scikit-learn -q

# Install and update the watermark package to display environment and library version information
%pip install -q -U watermark

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Data manipulation and visualization
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Pre-Processing and Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

In [3]:
# Load the watermark extension
%reload_ext watermark

# Display metadata for your notebook
%watermark -a "Maykon - 💬 Sentiment Analysis Project" -d -u -v -p numpy,pandas,matplotlib,seaborn

Author: Maykon - 💬 Sentiment Analysis Project

Last updated: 2026-03-16

Python implementation: CPython
Python version       : 3.14.0
IPython version      : 9.11.0

numpy     : 2.4.3
pandas    : 3.0.1
matplotlib: 3.10.8
seaborn   : 0.13.2

In [4]:
# Load the Sentiment Analysis dataset from a local CSV file into a pandas DataFrame
data = r"data\dataset.csv"

df = pd.read_csv(data)

In [5]:
# It returns the dimensions of the DataFrame as a tuple
df.shape

(2388, 75)

In [7]:
df.head(10) #Displays the first rows of the DataFrame df.

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,...,2022Q4,2023Q1,2023Q2,2023Q3,2023Q4,2024Q1,2024Q2,2024Q3,2024Q4,2025Q1
0,1,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,64.688709,61.319185,65.867074,68.262567,66.039285,62.452184,73.597480,75.162258,71.925035,70.263853
1,2,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,64.104215,64.183297,65.752729,65.954354,65.597731,65.374440,72.340776,72.275717,72.779925,74.291176
2,3,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.248269,0.237558,0.236841,0.235717,0.241366,0.233355,0.236395,0.238220,0.242984,0.235360
3,4,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.242981,0.240553,0.238109,0.236431,0.236390,0.235936,0.237543,0.239370,0.238111,0.239349
4,5,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,386.112317,426.972747,320.899060,297.709005,381.070358,428.160874,324.106184,300.675095,380.802186,453.832593
5,6,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,356.181839,351.659954,360.585785,356.274024,358.131407,362.286817,361.624871,366.993041,362.452924,366.114987
6,7,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,161.104979,162.432331,161.521244,162.742242,161.812556,161.213234,159.000930,159.576325,158.233082,158.150828
7,8,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,161.160560,161.888495,162.344945,162.440571,161.834364,160.805631,159.787676,159.143909,158.294445,157.729357
8,9,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,160.070361,202.983673,93.273901,66.468479,152.977150,204.262101,91.271379,65.698292,150.401085,225.182552
9,10,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,130.674082,125.347610,132.250003,127.642668,130.462923,135.870810,129.258876,135.334046,131.140442,133.855104

In [8]:
df.sample(15) # Random 15 rows

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,...,2022Q4,2023Q1,2023Q2,2023Q3,2023Q4,2024Q1,2024Q2,2024Q3,2024Q4,2025Q1
1062,1077,G20,NaN,NA120,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,20.738893,21.086748,20.061476,19.796076,20.838678,21.214153,20.100780,19.831582,20.760881,21.280786
1099,1114,G7,NaN,NA119,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.411820,0.406646,0.407218,0.415877,0.414954,0.416890,0.426414,0.433952,0.429677,0.437023
2371,2500,World,NaN,WLD,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,19.896900,20.126155,20.286861,20.486480,20.665319,20.928830,21.151074,21.345455,21.634252,22.178643
2177,2192,Western Asia,NaN,NAWA,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.908035,0.891686,0.907893,0.892647,0.897480,0.951214,0.946313,0.962354,0.995708,0.966640
111,112,Africa,NaN,NA605,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,3.923083,3.989296,3.987593,4.142980,4.235404,4.225334,4.105283,4.307823,4.270698,4.320389
259,274,Americas,NaN,AMETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,311.405194,319.010215,320.254823,320.392695,319.581243,314.422971,320.973375,321.089168,320.688454,318.230983
1912,1927,Southern Europe,NaN,NASE,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,3.288079,3.255776,3.284550,3.150688,3.311743,3.246070,3.323781,3.180134,3.362977,3.264825
599,614,Eastern Asia,NaN,NA510,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.211165,0.212981,0.212667,0.218684,0.216611,0.211945,0.213103,0.217288,0.208517,0.213969
1944,1959,Southern Europe,NaN,NASE,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.004167,0.003702,0.003820,0.003947,0.003718,0.003451,0.003756,0.003989,0.003815,0.003519
1001,1016,G20,NaN,NA120,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,3207.618812,3205.393977,3275.829111,3277.149541,3270.249068,3360.842950,3236.934529,3349.092507,3327.829056,3176.696375
2194,2209,Western Europe,NaN,NAWE,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,26.658768,27.207420,27.294723,27.498665,27.490858,27.168472,26.616248,26.519086,26.449649,26.359952
1783,1798,South-eastern Asia,NaN,NASEA,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,59.417314,59.084046,60.540899,62.033522,64.449331,66.450012,67.814723,70.171879,70.951130,74.815053
1489,1504,Northern Europe,NaN,NANE,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.423138,0.421789,0.420120,0.424076,0.430527,0.430844,0.432609,0.430317,0.426841,0.425207
128,129,Africa,NaN,NA605,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,111.240449,115.411728,109.350004,108.532488,114.646193,114.163063,109.821867,113.418790,117.087517,125.053615
2013,2028,Sub-Saharan Africa,NaN,SSA,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,2.562041,2.472218,2.522959,2.596343,2.630193,2.659433,2.593524,2.543358,2.585739,2.704583