## 🌍 Introduction

Climate change is one of the most important global challenges of our time. 🌱 Governments, researchers, and organizations around the world are increasingly using data to better understand how human activities affect the environment. By analyzing greenhouse gas emissions across countries, industries, and time periods, we can gain valuable insights into the patterns and trends that shape our planet’s climate. 📊

In this project, we explore a dataset containing quarterly indicators related to greenhouse gas emissions. The data allows us to observe how emissions evolve over time, how different industries contribute to environmental impact, and how patterns vary across countries and economic regions. Looking at these trends can help highlight which sectors play the largest role in emissions and where efforts toward sustainability might have the greatest impact. 🌎

To guide this analysis, the following key questions are considered:

🔎 **Research Questions**

* How have greenhouse gas emissions changed over time across countries and industries?
* Which industries contribute the most to overall emissions levels?
* Are there noticeable differences in emissions patterns between countries or economic regions?
* How do different gas types contribute to total emissions trends?

By answering these questions, this analysis aims to uncover meaningful insights from the data and better understand how economic activity and industrial sectors influence global emissions patterns. 📈✨

---

## 📂 Data Source

The dataset used in this project was obtained from the **Climate Change Indicators Dashboard** maintained by the International Monetary Fund.

This platform compiles climate-related indicators from multiple international sources to support research, policy development, and economic analysis related to climate change. 🌐

**Source:**
[https://climatedata.imf.org/datasets/543872e1d86c49e3a3bdf38f2b758f92/about](https://climatedata.imf.org/datasets/543872e1d86c49e3a3bdf38f2b758f92/about)

### 📥 Loading the Dataset and Libraries

Before we start, we need to install the necessary Python libraries and **load the dataset**.

In [1]:
# Install the required libraries
%pip install pandas numpy matplotlib seaborn scikit-learn -q

# Install and update the watermark package to display environment and library version information
%pip install -q -U watermark

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Data manipulation and visualization
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Pre-Processing and Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

In [3]:
# Load the watermark extension
%reload_ext watermark

# Display metadata for your notebook
%watermark -a "Maykon - 💬 Sentiment Analysis Project" -d -u -v -p numpy,pandas,matplotlib,seaborn

Author: Maykon - 💬 Sentiment Analysis Project

Last updated: 2026-03-17

Python implementation: CPython
Python version       : 3.13.7
IPython version      : 9.11.0

numpy     : 2.4.3
pandas    : 3.0.1
matplotlib: 3.10.8
seaborn   : 0.13.2

In [4]:
# Load the Sentiment Analysis dataset from a local CSV file into a pandas DataFrame
data = r"data\dataset.csv"

df = pd.read_csv(data)

In [5]:
# It returns the dimensions of the DataFrame as a tuple
df.shape

(2388, 75)

In [6]:
df.head(10) #Displays the first rows of the DataFrame df.

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,...,2022Q4,2023Q1,2023Q2,2023Q3,2023Q4,2024Q1,2024Q2,2024Q3,2024Q4,2025Q1
0,1,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,64.688709,61.319185,65.867074,68.262567,66.039285,62.452184,73.597480,75.162258,71.925035,70.263853
1,2,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,64.104215,64.183297,65.752729,65.954354,65.597731,65.374440,72.340776,72.275717,72.779925,74.291176
2,3,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.248269,0.237558,0.236841,0.235717,0.241366,0.233355,0.236395,0.238220,0.242984,0.235360
3,4,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.242981,0.240553,0.238109,0.236431,0.236390,0.235936,0.237543,0.239370,0.238111,0.239349
4,5,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,386.112317,426.972747,320.899060,297.709005,381.070358,428.160874,324.106184,300.675095,380.802186,453.832593
5,6,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,356.181839,351.659954,360.585785,356.274024,358.131407,362.286817,361.624871,366.993041,362.452924,366.114987
6,7,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,161.104979,162.432331,161.521244,162.742242,161.812556,161.213234,159.000930,159.576325,158.233082,158.150828
7,8,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,161.160560,161.888495,162.344945,162.440571,161.834364,160.805631,159.787676,159.143909,158.294445,157.729357
8,9,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,160.070361,202.983673,93.273901,66.468479,152.977150,204.262101,91.271379,65.698292,150.401085,225.182552
9,10,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,130.674082,125.347610,132.250003,127.642668,130.462923,135.870810,129.258876,135.334046,131.140442,133.855104

In [8]:
df.sample(10) # Random 15 rows

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,...,2022Q4,2023Q1,2023Q2,2023Q3,2023Q4,2024Q1,2024Q2,2024Q3,2024Q4,2025Q1
1450,1465,Northern Europe,NaN,NANE,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,8.551599,7.936843,7.980766,7.850102,7.805577,7.718130,7.891172,7.828424,7.863853,7.770800
99,100,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,4.662765,4.592910,4.638475,4.633543,4.613594,4.648860,4.633426,4.670584,4.669969,4.743332
1284,1299,Northern Africa,NaN,NANA9,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,48.011248,47.976508,48.681531,50.396582,50.754319,47.338665,47.864879,53.593234,52.884264,49.989040
145,146,Africa,NaN,NA605,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,0.801946,0.810947,0.820214,0.829365,0.825867,0.826504,0.845670,0.863317,0.872011,0.908773
377,392,Australia and New Zealand,NaN,NAANZ,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,3.028244,3.027211,3.054977,3.117176,3.133142,3.075913,3.075253,3.116960,3.019931,3.061998
370,385,Asia,NaN,ASIATMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,248.832342,258.625013,251.836361,255.958199,256.847651,268.759154,261.415457,263.206250,265.625152,277.243074
606,621,Eastern Asia,NaN,NA510,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,1122.722659,1128.669512,1120.446852,1184.438470,1160.288061,1168.008350,1121.507298,1203.819282,1165.249283,1124.654482
1516,1531,Northern Europe,NaN,NANE,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,213.611415,204.736852,196.962374,192.285102,203.804148,201.819496,195.302096,193.308628,205.420557,202.659390
95,96,Advanced Economies,NaN,AETMP,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,68.128784,67.634889,67.912289,68.662148,69.985910,70.429320,71.309210,71.766654,72.430215,74.072892
707,722,Eastern Europe,NaN,NAEE,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,142.940836,143.410855,143.464300,143.787781,143.913699,147.778700,148.804271,150.160964,152.562259,150.395416

In [9]:
df.tail() #Displays the last 5 rows of the DataFrame df.

,ObjectId,Country,ISO2,ISO3,Indicator,Unit,Source,CTS Code,CTS Name,CTS Full Descriptor,...,2022Q4,2023Q1,2023Q2,2023Q3,2023Q4,2024Q1,2024Q2,2024Q3,2024Q4,2025Q1
2383,2512,World,NaN,WLD,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,461.597897,463.399306,467.858827,472.314308,475.491386,477.755273,482.105839,489.264542,490.408500,494.987684
2384,2513,World,NaN,WLD,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,385.834429,393.086534,387.666238,387.794684,399.030287,406.843232,401.637057,398.964513,412.201171,424.677965
2385,2514,World,NaN,WLD,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,384.308985,386.096720,389.671794,394.225184,397.584046,398.709245,403.300465,405.857906,410.869060,416.101641
2386,2515,World,NaN,WLD,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,29.280399,29.322187,29.068810,29.581099,29.845763,30.088260,29.822110,30.175253,30.450210,30.837705
2387,2516,World,NaN,WLD,Quarterly greenhouse gas (GHG) air emissions a...,Million metric tons of CO2 equivalent,Organisation for Economic Co-operation and Dev...,ECNGA,Greenhouse Gas Emissions (GHG); Air Emissions ...,"Environment, Climate Change, Greenhouse Gas Em...",...,29.114959,29.104364,29.322747,29.662102,29.728647,29.899336,30.012889,30.204904,30.369061,30.660960

#### 🔎📊 Exploratory Data Analysis (EDA)

This is the stage where we start exploring the dataset to understand how greenhouse gas emissions behave across countries, industries, and time 🌍📊. The goal here is to identify patterns, trends, and potential anomalies that can guide the rest of the analysis 💡

During this phase, we use visualizations 📈 such as time series plots, comparisons between industries 🏭, and country-level analyses 🌎 to better understand how emissions evolve over time. We also rely on summary statistics to examine the distribution of values, detect missing data, and identify any inconsistencies in the dataset 🛠️

By performing this initial exploration, we build a solid understanding of the data, which helps ensure that any further analysis, transformations, or modeling steps are accurate and meaningful 🚀

In [10]:
# Information about the dataframe
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2388 entries, 0 to 2387
Data columns (total 75 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ObjectId             2388 non-null   int64
 1   Country              2388 non-null   str
 2   ISO2                 0 non-null      float64
 3   ISO3                 2388 non-null   str
 4   Indicator            2388 non-null   str
 5   Unit                 2388 non-null   str
 6   Source               2388 non-null   str
 7   CTS Code             2388 non-null   str
 8   CTS Name             2388 non-null   str
 9   CTS Full Descriptor  2388 non-null   str
 10  Industry             2388 non-null   str
 11  Gas Type             2388 non-null   str
 12  Seasonal Adjustment  2388 non-null   str
 13  Scale                2388 non-null   str
 14  2010Q1               2388 non-null   float64
 15  2010Q2               2388 non-null   float64
 16  2010Q3               2388 non-null   float64
 17  2010Q4               2388 non-null   float64
 18  2011Q1               2388 non-null   float64
 19  2011Q2               2388 non-null   float64
 20  2011Q3               2388 non-null   float64
 21  2011Q4               2388 non-null   float64
 22  2012Q1               2388 non-null   float64
 23  2012Q2               2388 non-null   float64
 24  2012Q3               2388 non-null   float64
 25  2012Q4               2388 non-null   float64
 26  2013Q1               2388 non-null   float64
 27  2013Q2               2388 non-null   float64
 28  2013Q3               2388 non-null   float64
 29  2013Q4               2388 non-null   float64
 30  2014Q1               2388 non-null   float64
 31  2014Q2               2388 non-null   float64
 32  2014Q3               2388 non-null   float64
 33  2014Q4               2388 non-null   float64
 34  2015Q1               2388 non-null   float64
 35  2015Q2               2388 non-null   float64
 36  2015Q3               2388 non-null   float64
 37  2015Q4               2388 non-null   float64
 38  2016Q1               2388 non-null   float64
 39  2016Q2               2388 non-null   float64
 40  2016Q3               2388 non-null   float64
 41  2016Q4               2388 non-null   float64
 42  2017Q1               2388 non-null   float64
 43  2017Q2               2388 non-null   float64
 44  2017Q3               2388 non-null   float64
 45  2017Q4               2388 non-null   float64
 46  2018Q1               2388 non-null   float64
 47  2018Q2               2388 non-null   float64
 48  2018Q3               2388 non-null   float64
 49  2018Q4               2388 non-null   float64
 50  2019Q1               2388 non-null   float64
 51  2019Q2               2388 non-null   float64
 52  2019Q3               2388 non-null   float64
 53  2019Q4               2388 non-null   float64
 54  2020Q1               2388 non-null   float64
 55  2020Q2               2388 non-null   float64
 56  2020Q3               2388 non-null   float64
 57  2020Q4               2388 non-null   float64
 58  2021Q1               2388 non-null   float64
 59  2021Q2               2388 non-null   float64
 60  2021Q3               2388 non-null   float64
 61  2021Q4               2388 non-null   float64
 62  2022Q1               2388 non-null   float64
 63  2022Q2               2388 non-null   float64
 64  2022Q3               2388 non-null   float64
 65  2022Q4               2388 non-null   float64
 66  2023Q1               2388 non-null   float64
 67  2023Q2               2388 non-null   float64
 68  2023Q3               2388 non-null   float64
 69  2023Q4               2388 non-null   float64
 70  2024Q1               2388 non-null   float64
 71  2024Q2               2388 non-null   float64
 72  2024Q3               2388 non-null   float64
 73  2024Q4               2388 non-null   float64
 74  2025Q1               2388 non-null   float64
dtypes: float64(62), int64(1), str(12)
memory usage: 1.4 MB

In [11]:
df.describe(include='all').T  # Generates descriptive statistics for all numeric columns in your DataFrame.

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ObjectId,2388.0,NaN,NaN,NaN,1213.093802,700.517297,1.0,611.75,1208.5,1805.25,2516.0
Country,2388,25,Advanced Economies,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ISO2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ISO3,2388,25,AETMP,100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Indicator,2388,1,Quarterly greenhouse gas (GHG) air emissions a...,2388,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2024Q1,2388.0,NaN,NaN,NaN,222.718239,890.758714,-0.0,0.83503,12.572202,87.390084,13405.758
2024Q2,2388.0,NaN,NaN,NaN,214.658705,855.148067,-0.338902,0.829891,11.940605,83.978671,13120.4639
2024Q3,2388.0,NaN,NaN,NaN,224.904458,905.813811,-0.0,0.851089,12.314523,84.015516,13540.92567
2024Q4,2388.0,NaN,NaN,NaN,223.765768,894.538794,-0.0,0.846428,12.659841,88.658769,13516.17495
2025Q1,2388.0,NaN,NaN,NaN,221.028479,873.136928,-0.589124,0.852849,12.651823,90.804491,13323.12557

##### Check for missing values on the DataFrame:

In [12]:
df.isna().sum()  # You can also use df.isnull().sum() — both do the same thing

ObjectId        0
Country         0
ISO2         2388
ISO3            0
Indicator       0
             ...
2024Q1          0
2024Q2          0
2024Q3          0
2024Q4          0
2025Q1          0
Length: 75, dtype: int64